# server port
server:
  port: '8080'

# mybatis
mybatis:
  # package aliases set
  type-aliases-package: com.dev.project.mapper
  # mapper xml set
  # mapper-locations: mybatis/mapper/*.xml, mybatis/mapper/**/*.xml
  mapper-locations: mybatis.mapper.main/*.xml 

# project setting
spring:

# view
  thymeleaf:
    cache: 'false'
    enabled: 'true'
    prefix: classpath:templates/
    suffix: .html
    
# datasource
  sql:
    init:
      platform: postgresql
  datasource:
    password: 'qwer1234'
    username: codej625
    hikari:
      maximum-pool-size: '4'
    url: jdbc:postgresql://localhost:5432/project

# devtools
  devtools:
    livereload:
      enabled: 'true'
